### ISSUE TITLE
active state results in runtime error

### ISSUE THREAD

**Issue by matthiaskern** [matthiaskern/css-blocks-hello-world#1]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/9108002/39264527-b9134746-48cd-11e8-9988-59ab894c0c0a.png">

Commented out for now:
https://github.com/matthiaskern/css-blocks-hello-world/blob/9f265a2812596bbbbe96e9f79971c73d6e75dd77/src/Button.jsx#L19

**Comment by chriseppstein** [comment]
This happens when the css-blocks styles are not rewritten.

**Comment by chriseppstein** [comment]
In dev mode, we should return a small object from `import styles from './Button.block.css';` that would be a proxy that gives a better runtime error.

**Comment by matthiaskern** [comment]
Fixed by #2.
